"""Record qualified build and concrete delivery plan before installed mutation."""
from work import *
build=json.loads((HERE/'build.json').read_text())
assert build.get('finished_at') and build['candidate_clean']
candidate=ROOT/'.pf/tmp/t10-operator-20260926/candidate'
patch=command('delivery-patch',['git','diff','40c9894227738472976546849047550415099486',build['candidate_commit'],'--'],cwd=candidate)
(HERE/'candidate.patch').write_text(patch,encoding='utf-8')
(HERE/'candidate-qualification.md').write_text('# Candidate qualification\n\nClean detached candidate '+build['candidate_commit']+' from installed predecessor 40c9894227738472976546849047550415099486. Exact '+str(len(build['delta']))+'-path qualified delta, including journal append serialization; main HEAD and dirty source preserved.\n\nSource focused assurance passed. Candidate checksums/schemas/public-cleanliness and metrics/server/profile/journal regressions passed. Official release-pack and release-archive-test quick passed; extracted metrics/server/profile/monitor/journal tests passed. Every '+str(build['archive_files_verified'])+' manifest-owned archive file verified.\n\nArchive: '+build['archive']+'\nSHA256: '+build['archive_sha256']+'\n\nInstalled updater read-only plan has no blockers/local conflicts/removals/Workplace operations. Counts: '+json.dumps(build['plan_counts'])+'. Exact patch: candidate.patch. Private candidate/extracted/QA fixtures are retained durable delivery evidence under .pf/tmp; no remote publication.\n',encoding='utf-8')
(HERE/'delivery-plan.md').write_text('# Concrete delivery plan\n\nUser explicitly authorized installed Core update and standard PF updater. Apply the qualified archive from build.json through installed core-update plan/apply/status. Recheck live owner and worker records, save current manifest/previous apply/Runtime state, stop only the verified named Runtime through its standard CLI, apply without force/conflict bypass, verify all installed hashes and automatic old/new-manifest/backed-up payload hashes, then restart with original port 0 / interval 2.0. Verify live monitor/server compact metrics, operator feature smokes, Runtime/Workplace doctors and preservation of protected config/unowned files/frozen artifacts/main source.\n\nNo Workplace migration is applicable. No host-owned MCP process kill or reload claim. Known plg-content-varreplace manifest warning is unrelated and preserved. Disk update, new subprocess/Runtime acceptance and actual connected host acceptance are distinct. Automatic backups and exact status are recorded in install.json; on failure reconcile official updater status before any retry.\n',encoding='utf-8')
print('Candidate and concrete official update plan recorded',flush=True)
