from pathlib import Path
import hashlib
import json
import subprocess

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parent
REL = OUT.relative_to(ROOT).as_posix()
common = '''You are a bounded implementation worker, not an auditor. Follow the primary design and fix only your assigned defects. No subagents, no lifecycle commands, no context refresh, no installs/restarts, no commits, no ACL or sandbox changes. Do not modify checksums, VERSION, release registrations or unrelated files. Primary owns integration and all PF transitions.
Use targeted rg/AST reads: Serena has no configured languages. Do not dump tools/processforge.py or scan all .pf. Aim for <= 20 focused tool calls; before code edits use at most 8 reads, each <= 180 lines. Write a failing regression from the supplied defect evidence, make the minimal repair, then run focused tests. On the FIRST sandbox PermissionError stop trying environment workarounds; preserve runnable tests and tell primary the exact command. You can still implement and perform static reasoning. No repeated broad exploration. Finish promptly with a concise report (<= 100 lines), exact changed files, actual test results vs unexecuted checks, risks. Use repo-relative paths in the report and describe absolute-path samples in words. Public tests use disposable temp fixtures, neutral names, no this-machine paths. Write report even on blockers.\n'''
specs = [
    ('a09-classifier', ['tools/processforge.py', 'tools/smoke_classifier_distribution_parity.py'], '''Fix A09. Inspect classify_project near 3630-3685, project_classifier_paths and freshness comparison near 10269; relevant local docs project-classification/context snapshot contracts. The defect is matched_rules[].source using project-relative source path versus basename under installed distribution despite identical classifier bytes. Prefer smallest stable owning-distribution-relative label with project-local resource behavior preserved; do NOT blindly strip provenance or suppress stale. Must retain real classifier changes, preserve existing source snapshot if possible, and prove parity with TWO disposable distribution roots (not modifying installed Core). Regression should fail old code, prove equal semantic classifier results, real rule/content change invalidation, local/Workplace classifier handling. Primary separately registers your smoke. See audit recovery classification_origin.stdout.json and probe_classification_origin.py. Avoid touching other CLI functions.'''),
    ('a01-search', ['src/processforge_core/local_resource_search.py', 'tools/smoke_search_file_root_containment.py'], '''Fix A01. Focus _iter_source_files around 352-390 and resource normalization only as needed. File root currently checks base against root.parent, allowing source ../secret.txt to index a sibling. Authorized file must remain the only readable file; directory sources must stay canonically within their root including discovered symlinks. Keep include/exclude behavior and dedup intact. Add positive authorized-file and directory tests, sibling/traversal/absolute source negatives, and symlink tests only when platform permits. Use existing audit native-core/audit_search_file_root_escape.py and local docs resource-search-index.md. Keep a real build_index/search negative marker test. Do not widen roots or alter project resource authorization.'''),
    ('a0310-runtime', ['tools/pf_runtime/service.py', 'tools/smoke_runtime_scheduler_failure_isolation.py', 'tools/smoke_runtime_singleton_orphan.py'], '''Fix A03, A04 and A10 together in service.py only. Existing primary probes: audit recovery verify_hooks.py (orphan_takeover and cache_read_failure) and parent probe_runtime_health.py. Inspect known_project_roots/scheduler_loop/status_payload/acquire_singleton/inspect_lifecycle. Requirements: missing assignment SystemExit and malformed host cache do not kill scheduler; isolate a bad project so a healthy project still ticks; report degraded health/error truthfully then recover when fixed; preserve shutdown KeyboardInterrupt/GeneratorExit behavior; live orphaned owner with mismatched OR missing lock cannot be acquired, including concurrent startup race; dead/stale recovery remains valid and one instance never deletes another lock. Do not merely add orphaned to one list while missing-lock acquire remains unsafe. Design bounded per-workplace lock critical section if needed using existing utilities (no new global infrastructure). Use real temp files and real child PIDs/threads in regressions, not only mocked inspect_lifecycle. Do not modify host.py: isolate project iteration from service.py or explain a precisely bounded handoff if truly necessary. Existing Runtime tests must stay compatible. Report exact guarantees and limitations.'''),
]
workers=[]
for task, public, detail in specs:
    (OUT/task).mkdir(exist_ok=True)
    brief=f'{REL}/{task}-brief.md'
    (ROOT/brief).write_text(common+'\n'+detail+'\n\nRead '+REL+'/design.md for governing architecture. Audit evidence root: .pf/artifacts/codebase-audit-20260910/.\n', encoding='utf-8')
    workers.append({'id':task,'title':task,'role':'worker','process':'task-batch-execution','objective':f'Implement the bounded repair brief {brief}', 'execution_mode':'implementation','writer':True,'model':'gpt-5.6-luna','reasoning_effort':'high','allowed_files':public+[f'{REL}/{task}/**',f'.pf/tmp/{task}/**'],'allowed_read_files':public+['src/processforge_core/**','tools/pf_runtime/**','tools/processforge.py','tools/*smoke*.py','tools/*helpers*.py','docs/concepts/**',f'{REL}/**','.pf/artifacts/codebase-audit-20260910/**','.pf/AGENTS.md','.pf/contexts/**'],'forbidden_files':['VERSION','CHANGELOG.md','checksums/**','.pf/artifacts/codebase-audit-20260910/**','.pf/process-forge.yaml'], 'required_sources':[brief,f'{REL}/design.md'],'required_outputs':[{'id':task+'-report','path':f'{REL}/{task}/report.md','type':'markdown','required':True}],'expected_report_artifact':f'{REL}/{task}/report.md','runtime_driver':'codex-exec','depends_on':[],'allow_subagents':False,'worker_may_rebuild_context':False})
plan={'schema_version':1,'run':{'id':'core-a01-a11-wave1-20260911','title':'A09 A01 and Runtime safety remediation','process':'multi-agent-task-orchestration'},'orchestrator':{'role':'orchestrator','responsibilities':['design','independent regression acceptance','sequential integration']},'runtime':{'default_driver':'codex-exec','supervisor_profile':'default','start_policy':'manual','max_parallel_workers':3},'workers':workers,'integration':{'required':True,'role':'orchestrator','expected_output':f'{REL}/integration-report.md'},'metadata':{'carrier_run':'garage-remediate-audited-a01-a11-defects-with-bounded-junior-pf-shell-wo','authorization':'Explicit user request to implement A01-A11 with PF shell workers; source-only scope.'}}
(OUT/'wave1-plan.yaml').write_text(json.dumps(plan,indent=2),encoding='utf-8')
tracked=subprocess.check_output(['git','ls-files'],cwd=ROOT,text=True).splitlines()
hashes={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in tracked if not p.startswith('.pf/') and (ROOT/p).is_file()}
(OUT/'baseline.json').write_text(json.dumps({'head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),'hashes':hashes},indent=2),encoding='utf-8')
print('Prepared three disjoint workers and baseline',len(hashes))
