from pathlib import Path
import json

OUT = Path(__file__).resolve().parent
ROOT = OUT.parents[2]
REL = OUT.relative_to(ROOT).as_posix()
template = json.loads((OUT/'wave1-plan.yaml').read_text())
common = (OUT/'a01-search-brief.md').read_text().split('Fix A01.')[0]
waves = {
  2: [
    ('a0206-reports', ['tools/processforge.py', 'tools/pf_runtime/host.py', 'tools/smoke_expected_report_containment.py', 'tools/smoke_authenticated_report_content.py'], '''Fix A02 first, then A06. Read bounded collector/expected_report_artifact/task_output_path in tools/processforge.py and host.py report authorization/automatic content checks. Old real evidence: recovery-20260911/verify_collection.py and collection-results.json under audit root. Requirements: a single safe project-relative resolver rejects absolute, traversal, drive-relative, Windows/UNC and escaping symlink paths BEFORE file reads in required outputs, worker-run start/collect and host report authorization. Keep legitimate project-relative files and exact expected-output equality. Existing containment helpers may be reused; do not alter unrelated public API. A06: allow absolute-path TEXT in authenticated PF-owned report only after valid task/run/native session/attempt/provenance/path/exact bytes/hash checks; keep secret scanning. Untrusted native assistant text remains filtered. Preserve durable raw ingestion, retry re-derivation and exactly one normalized message. Regression must use actual disposable worker collector+host ingestion, not a mock claiming success. Test traversal/absolute/symlink rejection with no external bytes in raw/chat/result, legitimate report collect twice exactly one, path-containing authenticated report collect twice exactly one, forged IDs/attempt/hash and secrets denied. Never rewrite legacy audit evidence. Primary owns integration registrations.'''),
    ('a05-migration', ['src/processforge_core/core_update.py', 'tools/smoke_core_update_migration_sources.py'], '''Fix A05. In core_update.py workplace_migration_plan currently accepts copy_if_missing source absent from ZIP; archive.read KeyError in apply leaves journal applying. Validate archive source declarations (missing, directory, invalid path) during planning BEFORE target mutations; keep optional/already-present semantics justified by contract. Apply must fail with structured status and recoverable journal/backup if an archive/read/extraction failure still occurs after planning (test fault at apply boundary). Do not swallow programmer errors broadly. Read audit native-core/audit_core_update_missing_migration_source.py and smoke_core_update_manifest.py, local docs update/migration contract. Real minimal ZIP regression: malformed manifest missing member plan blocked, no target change, positive migration passes and existing target preserved. Test post-plan read fault journal not applying. Do not operate installed distribution/workplace or bump versions.'''),
    ('a08-jsonrpc', ['tools/pf_runtime/mcp_server.py', 'tools/smoke_mcp_jsonrpc_validation.py'], '''Fix A08 in native stdio MCP. Current respond/main accepts jsonrpc 1.0 and coerces list params/arguments to {} and responds to notifications. Validate JSON-RPC 2.0 envelope, method/id types (bool is not numeric ID), params and tools/call arguments using existing advertised tool schema constraints before dispatch. Preserve missing optional args/defaults and valid clients. Errors: parse -32700; invalid envelope -32600; invalid params/schema -32602; unknown method -32601. Valid notifications never emit responses including tools/call errors, but valid mutating notifications retain the chosen spec-compliant dispatch behavior. Distinguish id absent from explicit null. Use local JSONRPC/MCP docs or existing tests, no new third-party dependency. Regression sends real newline-framed requests to source native stdio MCP with disposable workplace, tests malformed JSON recovery, wrong protocol/method/id, params and arguments arrays/scalars, required/type/unknown arguments, valid initialize/list/tool call, notification silence using subsequent sentinel response. A fake runtime can supplement dispatch count but is not sole protocol proof. Do not change business/session logic.''')
  ],
  3: [
    ('a07-session', ['tools/processforge.py', 'tools/pf_runtime/session_read.py', 'tools/smoke_session_identity_roundtrip.py'], '''Fix A07 exact opaque session identity. agent_presence_path/find_agent_presence/checkin currently safe_id lossy lowercase/slugs, session_read rejects Case-Session despite successful checkin. Introduce collision-resistant filenames (hash exact UTF-8 identity or equivalent), with exact metadata identity check and backward reading of valid legacy lowercase/mixed-case entries. Never casefold incoming IDs, never overwrite another exact ID via normalized collision; handle checkout/recovery/update callers consistently. Read bounded function definitions/calls and session_read projection. Regression actual agent-checkin then source native MCP pf.session_context/chat or other existing session read: lowercase, mixed-case and two colliding slug IDs independently retrievable; checkout one must preserve other. Legacy fixture read compatibility and forged metadata rejected. Primary owns registration; do not edit unrelated CLI or archive metadata.'''),
    ('a11-hooks', ['tools/pf_runtime/codex_hooks.py', 'tools/smoke_codex_lifecycle_identity.py'], '''Fix A11 normalized_event ID collision SessionStart startup vs resume. Existing hook ID codex:hook:session:turn:tool loses source/type. Include stable lifecycle fact discriminator so startup and resume events survive actual raw ingress in same session, while repeat delivery of one fact remains idempotent. Preserve tool completion semantics and existing provider event IDs when available; explicitly state limits if repeated resume occurrences lack provider identity, do not invent random id or wall time that breaks retry dedup. Regression normalized inputs then real host.ingest_event in isolated workplace with session routing: startup,resume,repeated resume yields two events with proper types and duplicate semantics. See audit recovery-20260911/verify_hooks.py. H01 is rejected audit hypothesis: do NOT suppress hook delivery retries globally or alter background dispatcher.''')
  ]
}
for number, specs in waves.items():
    plan = json.loads(json.dumps(template))
    plan['run']['id'] = f'core-a01-a11-wave{number}-20260911'
    plan['run']['title'] = f'A01-A11 remediation wave {number}'
    plan['workers'] = []
    for task, public, detail in specs:
        (OUT/task).mkdir(exist_ok=True)
        brief=f'{REL}/{task}-brief.md'
        (ROOT/brief).write_text(common+'\n'+detail+'\n\nGoverning design: '+REL+'/design.md. Audit root: .pf/artifacts/codebase-audit-20260910/.\n',encoding='utf-8')
        worker=json.loads(json.dumps(template['workers'][0]))
        worker.update(id=task,title=task,objective=f'Implement bounded repair brief {brief}',allowed_files=public+[f'{REL}/{task}/**',f'.pf/tmp/{task}/**'],required_sources=[brief,f'{REL}/design.md'],required_outputs=[{'id':task+'-report','path':f'{REL}/{task}/report.md','type':'markdown','required':True}],expected_report_artifact=f'{REL}/{task}/report.md')
        worker['allowed_read_files'] = public + ['src/processforge_core/**','tools/pf_runtime/**','tools/processforge.py','tools/*smoke*.py','tools/*helpers*.py','docs/concepts/**',f'{REL}/**','.pf/artifacts/codebase-audit-20260910/**','.pf/AGENTS.md','.pf/contexts/**']
        plan['workers'].append(worker)
    (OUT/f'wave{number}-plan.yaml').write_text(json.dumps(plan,indent=2),encoding='utf-8')
    print('Prepared wave',number)
