from pathlib import Path
import subprocess, json, hashlib, datetime

ROOT=Path(__file__).resolve().parents[3]
BASE=Path('.pf/artifacts/core-f03-f05-20260910')
RUN='core-f03-f05-shell-20260910'
CARRIER='garage-remediate-python-core-audit-f03-f04-f05-evidence-freshness-and-re'
def write(name,text):
    path=ROOT/BASE/name; path.parent.mkdir(parents=True,exist_ok=True); path.write_text(text,encoding='utf-8')
def dump(name,data): write(name,json.dumps(data,indent=2)+'\n')
tracked=subprocess.check_output(['git','ls-files','-z'],cwd=ROOT).decode().split('\0')
public={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in tracked if p and not p.startswith('.pf/') and (ROOT/p).is_file()}
dump('baseline.json',{'head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),'files':public,'status':subprocess.check_output(['git','status','--short'],cwd=ROOT,text=True)})
(ROOT/BASE/'baseline.diff').write_bytes(subprocess.check_output(['git','diff','--binary'],cwd=ROOT))
(ROOT/BASE/'baseline-process_execution.py').write_bytes((ROOT/'src/processforge_core/process_execution.py').read_bytes())
common='''
Read your PF assignment, immutable capsule and this brief first. You are a bounded PF shell worker. Primary owns lifecycle, acceptance, checksums and integration. Do not start Work, modify assignment/run/capsule, collect workers, refresh context, commit/push/publish, install or repair Runtime/MCP/hooks/Workplace. No new dependencies. Preserve all pre-existing dirty work including F01/F02 and docs. Only edit allowed files. Audit input artifacts are immutable: do not execute their reproduction scripts in place (they overwrite evidence). Public tests must work in an extracted distribution without Git or private .pf files. Standard tempfile.TemporaryDirectory fixtures only; private repository scratch only under your assigned .pf/tmp scope. No hardcoded machine paths or sandbox workarounds in public files. If a test encounters sandbox TemporaryDirectory WinError 5 once, stop execution experiments, report the limit, and finish source/report; primary runs genuine tests. Do not change TMP, use alternate drive scratch, monkeypatch temp cleanup, or weaken tests. Serena symbol extraction was attempted and fails Active languages []; bounded reads/AST are approved fallback. No platform/toolchain is selected in current context. Consult local docs and existing Python smoke patterns. Write append-only log.md and final report.md in your owned evidence directory, with files, reasoning, exact checks actually executed, failures/limits, and Git-history origin. A report must not equate inspection with a test PASS. No nested workers.
'''
briefs={
'f0304-evidence':'''# F03/F04: latest applicable evidence and file freshness
Implement minimal fixes in src/processforge_core/process_execution.py; add portable regression tools/smoke_work_evidence_freshness.py. Own those two public files only. Read audit report F03/F04, private reproduce_integration.py as reference, process_execution_smoke_support.py, state/transition/can_complete and existing related smokes. Inspect Git history for origin.
Architecture: choose latest applicable evidence by identity FIRST, then evaluate status; never resurrect an older PASS behind a failed/stale/latest unknown status. Input accepts input/artifact aliases in chronological evidence order; same identity across those kinds supersedes. Current-stage outputs and exit gates still require current execution evidence; required inputs/entry/run completion gates may use accumulated evidence. Reentering a stage must not reuse its old outputs. Fix evidence merge identity for evidence_id if needed, without changing unrelated identifiers.
For every selected file-backed evidence required by readiness/transition (including gate paths and accumulated inputs/run gates), re-resolve safe project path, require regular file and stored SHA256 match. Missing/changed/unsafe/unreadable or missing digest => unsatisfied with explicit diagnostic, never exception or historical positive fallback. Do not mutate stored history during read-only state. Existing pathless attestations remain supported. Only validate depended-on evidence; obsolete/unrelated files must not block work. Re-submitting current existing content records new digest and recovers normally. Note TOCTOU limit rather than introducing giant locking/refactor.
Regression matrix with real temporary PF fixture and service/MCP paths: historical PASS then current FAIL on input AND gate blocks advancement; FAIL then PASS recovers; artifact/input cross-kind order; unrelated IDs do not supersede; reentry requires new outputs; deleted and changed saved files block both state and transition; resubmission fixes digest; obsolete/unrelated files do not block; saved gate file and run completion gate freshness; required evidence identifiers do not overwrite unrelated evidence. Include positive normal completion. Keep fixture count bounded, reuse fixtures with controlled cases where possible. Public tests assert fixed behavior only. Primary will run tests and replace only core module in isolated copy to show before-fix failure.
Do not implement F05 completion recovery in this scope. Handoff your design/testing and source ownership to primary for sequential F05 worker.
''',
'f05-completion':'''# F05: recoverable terminal completion
Start ONLY after f0304-evidence collected and primary accepted. Read its report and preserve its changes. Own src/processforge_core/process_execution.py and new tools/smoke_work_completion_recovery.py; do not edit F03/F04 smoke. Inspect original F05 audit reproduction and Git history.
Design a minimal durable completion-intent journal under this run directory, written atomically BEFORE terminal assignment/run changes, containing validated intended final payloads/metadata needed for deterministic replay. Under existing run lock, retry of ordinary transition must detect pending intent BEFORE terminal short circuit and idempotently finish assignment, run tasks/status, summary, handoff, task index and projections; preserve original completion time/history, no duplicate terminal history. Recover via explicit run/assignment and normal selection where feasible. Pin and journal ownership/path must be checked; never trust arbitrary journal paths. Never auto-complete old arbitrary terminal mismatches without a matching intent. Normal already-completed work without pending intent retains terminal behavior. Journal removal only after all mandatory writes succeed. Review transition emissions: ensure replay does not falsely claim exactly-once events; use existing deterministic event support if available or explicitly document bounded delivery semantics. Include complete() route and discovery of pending terminal runs in design. Primary will adjudicate contract before acceptance.
Regression: genuine temporary PF project; one-shot injected failure before/after each durable completion write (intent, assignment, run, summary, handoff, index, projection and journal cleanup as applicable), fresh service retry via ordinary API converges; restored original time and exactly one final history record; run task status done, terminal assignment/run, correct summary/handoff/index; no partial evidence revalidation permits a different outcome to rewrite committed intent; repeated completed call safe; malformed/mismatched journal fails closed. Preserve F03/F04 negative semantics, and ordinary stage transitions. Public test portable without Git/private evidence dependencies. No infrastructure repair. No tools/processforge.py edit without primary handoff.
''',
'f0305-assurance':'''# Independent assurance of F03-F05
After both implementation scopes complete, analyze actual source/regressions and primary validation artifacts. Report-only ownership: your evidence/scratch. Run portable smokes if sandbox permits; on known temp error stop and distinguish primary evidence from your tests. Independently assess test strength: later FAIL, alias/reentry, file mutations, selected-only semantics, terminal fault points and fresh-service retries. Probe a missing edge in an isolated fixture if useful. Report concrete failures with reproducer; no product edits. Check both before-fix FAIL and after-fix PASS evidence. Give PASS/FAIL with exact limits.
''',
'f0305-review':'''# Independent final code review
After implementation and assurance, review final diff against baseline-process_execution.py and source smokes, design and primary evidence. Report-only. Focus latest evidence identity/status, safe hash checks without hidden mutable state, recovery ordering/selection, partial I/O/fresh-service retry, tampered intent, history/time/idempotence and ordinary completion/transition compatibility. Identify concrete defects with lines/reproduction, not speculative refactors. Verify preserved F01/F02 work. Never accept test reports as proof if raw evidence contradicts them. Record actual checks and final PASS/FAIL plus bounded residual risks.
'''}
workers=[]
for index,(name,brief) in enumerate(briefs.items()):
    write(name+'-brief.md',brief+common)
    own=['src/processforge_core/process_execution.py',('tools/smoke_work_evidence_freshness.py' if index==0 else 'tools/smoke_work_completion_recovery.py')] if index<2 else []
    workers.append({'id':name,'title':brief.splitlines()[0][2:],'role':'worker' if index<2 else 'reviewer','process':'task-batch-execution','objective':f'Execute bounded brief {BASE.as_posix()}/{name}-brief.md','execution_mode':'implementation' if index<2 else 'assurance','writer':index<2,'model':'gpt-5.6-luna','reasoning_effort':'high','allowed_files':own+[f'{BASE.as_posix()}/{name}/**',f'.pf/tmp/core-f03-f05-20260910/{name}/**'],'allowed_read_files':['src/**','tools/**','docs/**','schemas/**','processes/**','templates/**','.pf/contexts/project-context.snapshot.yaml','.pf/artifacts/python-core-audit-20260908/**',f'{BASE.as_posix()}/**'],'forbidden_files':['VERSION','CHANGELOG.md','checksums/**','tools/processforge.py','.pf/process-forge.yaml','.pf/artifacts/python-core-audit-20260908/**'],'required_sources':[f'{BASE.as_posix()}/{name}-brief.md'],'required_outputs':[{'id':name+'-report','path':f'{BASE.as_posix()}/{name}/report.md','type':'markdown','required':True}],'expected_report_artifact':f'{BASE.as_posix()}/{name}/report.md','runtime_driver':'codex-exec','depends_on':[] if index==0 else [list(briefs)[index-1]],'allow_subagents':False,'worker_may_rebuild_context':False})
dump('orchestrator-plan.yaml',{'schema_version':1,'run':{'id':RUN,'title':'F03-F05 evidence integrity and recoverable terminal transition','process':'multi-agent-task-orchestration'},'orchestrator':{'role':'orchestrator','responsibilities':['architecture and sequential ownership','real regression acceptance','integration and governed closure']},'runtime':{'default_driver':'codex-exec','supervisor_profile':'default','start_policy':'manual','max_parallel_workers':1},'workers':workers,'integration':{'required':True,'role':'orchestrator','expected_output':f'{BASE.as_posix()}/integration-report.md'},'metadata':{'carrier_run':CARRIER,'authorization':'User explicitly requests next F03-F05 batch using junior PF shell workers. Sequential dependency transfers the shared source scope; no parallel writers.'}})
write('plan.md','''# F03-F05 orchestration and design
Status: planned. Separate specialized shell run preserves the pinned task-batch carrier.
1. Preserve current public bytes and prior accepted work; fresh source context and read immutable carrier capsule.
2. Luna/high f0304-evidence owns evidence identity/freshness implementation plus one smoke.
3. After primary acceptance and collection, Luna/high f05-completion inherits shared source ownership and owns its separate recovery smoke. No concurrent writes.
4. After implementation, Luna/high independent assurance then review; primary validates actual positive/negative and fault-injection tests in clean public copies.
5. Primary owns checksum and any test registration, focused integration checks, preservation and closeout. Prior baseline Runtime startup failure is separate; no full release claim. F06-F12 follow later.
No commit/push/release, installed infrastructure actions, version or unrelated fixes.
Evidence design: latest matching identity before status; selected file proofs revalidated on state/transition; stage output scope preserved. Completion design: durable intent, replay under run lock before terminal check; restore all terminal files with deterministic history/time.
''')
dump('intake-evidence.json',[{'kind':'artifact','artifact_id':'run-record','status':'ready','path':f'{BASE.as_posix()}/baseline.json'},{'kind':'gate','gate_id':'run-has-context','status':'passed','summary':'Current source context fresh, carrier capsule read and accepted prior work preserved in baseline.'}])
dump('planning-evidence.json',[{'kind':'artifact','artifact_id':'task-index','status':'ready','path':f'{BASE.as_posix()}/orchestrator-plan.yaml'},{'kind':'gate','gate_id':'run-has-tasks','status':'passed','summary':'Sequential scopes with explicit ownership and post-implementation independent validation.'}])
log=ROOT/'.pf/logs/core-f03-f05-orchestrator-20260910.md'
log.write_text(f'''# F03-F05 orchestrator log
## {datetime.datetime.now().isoformat(timespec='minutes')} - orchestrator
Task: Governed remediation F03-F05 using junior PF shell workers.
Files analyzed: .pf rules, current context, previous handoff, process_execution.py, existing smokes, Git history.
Files changed: private baseline, plan, briefs and evidence only.
Templates used: orchestrator-task-plan; task-batch carrier.
Tools used: source CLI, Serena attempted (no active languages), bounded shell/AST fallback.
Decisions: sequential shared file ownership; primary acceptance then independent assurance/review. Context source CLI fresh; connected MCP stale, no infrastructure repair.
Risks: prior Runtime startup baseline failure separate; preserve all dirty public bytes outside scope. Workers must stop on sandbox temp error and hand genuine execution to primary.
Next steps: validate/materialize plan, transition carrier, launch first worker.
Handoff: {BASE.as_posix()}/*-brief.md
''',encoding='utf-8')
print('Created baseline, 4 briefs, plan and intake/planning evidence.')
