"""Produce truthful delivery/evolution evidence only after installed verification."""
from work import *
build=json.loads((HERE/'build.json').read_text());install=json.loads((HERE/'install.json').read_text())
assert build.get('finished_at') and install.get('finished_at') and install['preservation']=='PASS'
update=install['apply'];assert update['status']=='applied'
text='# Delivered operator completion and journal fix\n\n'
text+='Installed candidate '+build['candidate_commit']+' using official core-update apply, update '+update['update_id']+'.\n'
text+='Archive: '+build['archive']+'\nSHA256: '+build['archive_sha256']+'\nBackup: '+update['backup_dir']+'\n\n'
text+='Verified all '+str(install['installed_hashes_verified'])+' owned installed payload hashes and '+str(install['backup_hashes_verified'])+' prior payload backups plus old/new manifests. Config, unowned files, historical artifacts, main HEAD and dirty source preserved. No Workplace migration. Runtime restarted through standard commands with original port 0 / interval 2.0; new instance '+install['new_instance']+', observed PID '+str(install['new_pid'])+'. Re-read owner before future lifecycle action.\n\n'
text+='Original 18 source checks plus focused six-file delivery correction reassessment, clean candidate validation, official archive quick suite, extracted metrics/server/profile/monitor/journal checks, installed feature smokes, Runtime doctor and Workplace doctor passed. Actual installed server status publishes compact activity metrics independently of slow scheduler routing; partial project coverage stays explicit. The unrelated registered plg-content-varreplace missing-manifest warning is preserved. Profile tests changed isolated fixtures only.\n\n'
text+='Release notes: bounded TTL-qualified session/worker/Run/lease observations; guarded server start/run/status/stop/restart and launchers; explicit diagnostics profile plan/apply with locks and expiry; Windows native PID observation; serialized dedup/append/fsync for mandatory journal writes. Compatibility: old runtime commands and v1 diagnostics remain; old metrics-less servers display unknown; default server stop refuses unsupported/busy/unknown owners, force is explicit. Native tray/executable and remote web are outside this terminal slice.\n\n'
text+='Migration: no project or Workplace rewrite required. Delivery patch: candidate.patch. Initial a5eeac53 installation and its failed live observation are retained in ../t10-operator-20260926/; corrected final build/update commands, hashes and preservation evidence: build.json, core-update-plan.json, final-update-plan.json, install.json and command result files. Automatic updater backup retained; no manual installed payload copies. Private candidates/extractions/backups under .pf/tmp are durable evidence.\n\n'
text+='Connected host boundary: new Runtime and installed subprocess behavior verified; host-owned MCP was not restarted and no live reconnect acceptance is claimed. Earlier MCP 60-second post-mutation timeouts use reconciled standard Work CLI fallback. T07 engine implementation is explicitly authorized and remains next; its prior design-only documents are historical, not an implementation claim.\n'
(HERE/'delivery.md').write_text(text,encoding='utf-8')
(HERE/'evolution.md').write_text('# Evolution\n\nCompleted local T10 operator slice and standard installed delivery, including preceding journal serialization fix. Distinguish registration, TTL presence, running records and actual process health; partial bounded observations must not become exact zero. Pause Runtime admission before guarded worker checks to prevent scheduler/request races. Native zero-time Windows handle observation avoids tasklist startup latency without relaxing network deadlines. Test timestamp precision must match serialized ISO precision.\n\nRetain source/archive/installed/connected-host evidence separately; preserve failed historical observations with corrections rather than rewriting immutable artifacts. Update remains manifest-owned, serialized and backed up. Next authorized responsibility is T07 engine I01 feasibility then versioned implementation/acceptance, following the existing specification and without silently claiming mediation of native Codex/CLI routes. No new global policy or external publication.\n',encoding='utf-8')
(ROOT/'.pf/handoffs/t10-operator-20260926.md').write_text(text+'\nCurrent Work: '+RUN+' / '+ASSIGN+'. Release/evolve transitions and final doctor still to be recorded before closeout.\n',encoding='utf-8')
print('Delivery and evolution evidence written',flush=True)
